
# Gem::Specification for Github-0.1.1
# Originally generated by Echoe

Gem::Specification.new do |s|
  s.name = %q{github}
  s.version = "0.1.1"
  s.date = %q{2008-03-26}
  s.summary = %q{The official `github` command line helper for simplifying your GitHub experience.}
  s.email = %q{chris@ozmm.org}
  s.homepage = %q{http://github.com/}
  s.rubyforge_project = %q{github}
  s.description = %q{The official `github` command line helper for simplifying your GitHub experience.}
  s.default_executable = %q{github}
  s.has_rdoc = true
  s.authors = ["Chris Wanstrath"]
  s.files = ["bin/github", "commands/commands.rb", "commands/helpers.rb", "lib/github/command.rb", "lib/github/helper.rb", "lib/github.rb", "LICENSE", "README", "spec/command_spec.rb", "spec/helpers/owner_spec.rb", "spec/helpers/project_spec.rb", "spec/helpers/public_url_for_spec.rb", "spec/helpers/repo_for_spec.rb", "spec/helpers/user_and_repo_from_spec.rb", "spec/helpers/user_for_spec.rb", "spec/spec_helper.rb", "Manifest", "github.gemspec"]
  s.executables = ["github"]
end


# # Original Rakefile source (requires the Echoe gem):
# 
# require 'rubygems'
# require 'rake'
# 
# begin
#   require 'echoe'
# 
#   Echoe.new('github', '0.1.1') do |p|
#     p.rubyforge_name = 'github'
#     p.summary      = "The official `github` command line helper for simplifying your GitHub experience."
#     p.description  = "The official `github` command line helper for simplifying your GitHub experience."
#     p.url          = "http://github.com/"
#     p.author       = 'Chris Wanstrath'
#     p.email        = "chris@ozmm.org"
#   end
# 
# rescue LoadError => boom
#   puts "You are missing a dependency required for meta-operations on this gem."
#   puts "#{boom.to_s.capitalize}."
# end
